## Basic functions

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
nested_list = [[1,2],[3,4],[5,6]]

In [5]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [6]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace(0,10,5) #Divide el intervalo en tantas partes como digamos n+1

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.eye(5) #MatrizIdentidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(2)

array([0.72048759, 0.75131615])

In [31]:
np.random.rand(3,4)

array([[0.43482194, 0.99478626, 0.83467514, 0.56281712],
       [0.13960255, 0.60263773, 0.48527233, 0.2967418 ],
       [0.17981084, 0.4609871 , 0.67599795, 0.15879747]])

In [33]:
np.random.randn(5,5)    #Normal distribution

array([[ 0.29899289,  1.75981536, -0.19066114, -0.24059153, -0.25605775],
       [-0.09085574, -0.66852486,  0.23688615,  2.40282818, -0.35128605],
       [-0.72461285,  1.2605442 , -0.77110942, -1.35518145, -1.39636681],
       [ 0.39879757,  0.52286408,  0.1990985 ,  1.81434941,  0.55668136],
       [ 0.25714859, -3.20915072, -1.13671324, -0.02903178, -0.68009646]])

In [37]:
np.random.randint(1,100,(1,2))

array([[14, 66]])

In [42]:
np.random.seed(42) #Establecer semilla

In [44]:
np.random.rand(4) #Same numbers

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [45]:
arr = np.arange(25)

In [46]:
ranarr = np.random.randint(0,50,10)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [52]:
arr.shape

(25,)

In [59]:
np.reshape(arr,(5,5)) #Error si hay distinto numero de elementos 
# arr.reshape(5,6)
arr.shape #No modifica el array directamente

(25,)

In [60]:
arr = arr.reshape(5,5)

In [61]:
arr.shape

(5, 5)

In [69]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [64]:
ranarr.max()

43

In [65]:
ranarr.argmax() #Index location

7

In [66]:
ranarr.min()

1

In [71]:
ranarr.argmin()

5

In [72]:
ranarr.dtype

dtype('int32')

## Indexing and selection

In [73]:
import numpy as np

In [75]:
arr = np.arange(0,11)

In [76]:
arr[8]

8

In [77]:
arr[1:5]

array([1, 2, 3, 4])

In [78]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [79]:
arr[:5]

array([0, 1, 2, 3, 4])

In [80]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr[0:5] = 100

In [83]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [84]:
arr = np.arange(0,11)

In [85]:
slice_of_arr = arr[0:5]

In [86]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
slice_of_arr[:] = 99 #Broadcasting

In [89]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [90]:
arr # Have suffer some changes because it was defined with the other array

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy() #Usa una copia si no quieres modificar

In [91]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [93]:
arr_2d.shape

(3, 3)

In [97]:
arr_2d[1,1] #Empieza en el cero

25

In [101]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [102]:
arr = np.arange(0,11)

In [103]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [105]:
bool_arr = arr>4

In [106]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [109]:
arr[bool_arr] #One type

array([ 5,  6,  7,  8,  9, 10])

In [110]:
arr[arr>4] #Another type 

array([ 5,  6,  7,  8,  9, 10])

## Numpy Operations

In [111]:
import numpy as np

In [113]:
arr = np.arange(0,10)

In [114]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
arr + 5 #All the elements

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [118]:
arr + arr #Same length

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [119]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [121]:
arr / arr #Gets a warning but it runs in numpy arrays

C:\Users\Pedro Delgado Jiméne\AppData\Local\Temp\ipykernel_8616\1259378818.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr #Gets a warning but it runs in numpy arrays


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [123]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [124]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [125]:
np.log(arr)

C:\Users\Pedro Delgado Jiméne\AppData\Local\Temp\ipykernel_8616\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [126]:
arr.std()

2.8722813232690143

In [127]:
arr.mean()

4.5

In [130]:
arr2d= np.arange(0,25).reshape(5,5)

In [131]:
arr2d.sum()

300

In [134]:
arr2d.sum(axis=1)# Columnas y 0 por filas

array([ 10,  35,  60,  85, 110])

In [135]:
arr2d.sum(axis=0) # Por filas

array([50, 55, 60, 65, 70])

## Numpy Exercises

In [ ]:
import 